### ISSUE TITLE
Socat uses 100% when odoo is stopped

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/docker-whitelist#1]
When using this in doodba-scaffolding and stopping socat sometimes uses 100% of the CPU:
```
top - 10:06:13 up  1:59,  4 users,  load average: 3,31, 4,00, 4,01
Tasks: 530 total,   5 running, 393 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4,8 us,  7,3 sy,  0,0 ni, 87,9 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem : 32937164 total,  9793444 free, 10869704 used, 12274016 buff/cache
KiB Swap: 33484796 total, 33483260 free,     1536 used. 20933540 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                 
26513 root      20   0   14584    360      0 R 100,0  0,0  10:40.81 socat tcp-listen:8069,fork,reuseaddr tcp-connect:odoo:8069   
```

Currently the image is using socat version 1.7.3.1 (from 2016):
```
bigbear3001@wt-io-it-bigbear3001:~$ docker run tecnativa/whitelist socat -V
socat by Gerhard Rieger - see www.dest-unreach.org
socat version 1.7.3.1 on Apr 29 2016 22:10:44
   running on Linux version #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019, release 4.15.0-54-generic, machine x86_64
features:
...
```

It seems that 1.7.3.2 (from 2017) whould fix this issue: http://www.dest-unreach.org/socat/.
Would it be ok to have a patch where socat is installed from tar.gz instead of from the alpine repos? or upgrade to alpine 3.6 which would have this version i guess:
https://pkgs.alpinelinux.org/package/v3.6/main/ppc64le/socat

**Comment by pedrobaeza** [comment]
@Yajo is on holidays. He will answer when he comes back.

**Comment by ap-wtioit** [comment]
@pedrobaeza thanks for the info

just rebuilding the image should be enough to solve this (i get socat version 1.7.3.3 when i build the image on my local system)

**Comment by Yajo** [comment]
I triggered a rebuild in the Docker Hub, thanks for the report.
