### ISSUE TITLE
How to use to expose ports

### ISSUE THREAD

**Issue by qm3ster** [Tecnativa/docker-whitelist#2]
How does this solve the
> Exposing ports from a container while still not letting the container access the WWW

usage listed in the README?
I see traefik used for that in the example instead

**Comment by Yajo** [comment]
Use [this pattern](https://github.com/Tecnativa/doodba-copier-template/blob/6d74cfb68665039c407e94c7532fcd41d73212d4/tests/default_settings/v13.0/devel.yaml#L4-L16).
