### ISSUE TITLE
Errors on  AWS / RDS

### ISSUE THREAD

**Issue by HJessDK** [Tecnativa/docker-whitelist#5]
We deployed some staging servers without any issues, but suddenly our RDS (Postgres) won't answer throw the proxy anymore, it almost the same setup on all our amazon EC2 instances. 

The globalwhitelist in our setup looks like this

[docker-compose.txt](https://github.com/Tecnativa/docker-whitelist/files/5819707/docker-compose.txt)

It seems to "work" as i can ping and resolve the RDS host
```
$ cd /opt/odoo/docker ; docker-compose exec odoo bash

odoo@hobbii:/opt/odoo$ ping staging.amazon.rds
PING staging.amazon.rds (192.168.0.4) 56(84) bytes of data.
64 bytes from globalwhitelist_amazon_rds_stageing_1.globalwhitelist_shared (192.168.0.4): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from globalwhitelist_amazon_rds_stageing_1.globalwhitelist_shared (192.168.0.4): icmp_seq=2 ttl=64 time=0.024 ms
64 bytes from globalwhitelist_amazon_rds_stageing_1.globalwhitelist_shared (192.168.0.4): icmp_seq=3 ttl=64 time=0.022 ms

odoo@hobbii:/opt/odoo$ telnet staging.amazon.rds 5432
Trying 192.168.0.4...
Connected to staging.amazon.rds.
Escape character is '^]'.
```

But this fails..

```
odoo@hobbii:/opt/odoo$ echo $PGHOST
staging.amazon.rds
odoo@hobbii:/opt/odoo$ echo $PGUSER
odoo
odoo@hobbii:/opt/odoo$ echo $PGPASSWORD
********************

psql -h staging.amazon.rds -U odoo  #Timeouts 
```

in our docker instance (odoo) I get the following message
```
hjess@odoo-staging-v2:/opt/odoo/docker$ docker-compose logs -f
Attaching to docker_odoo_1, docker_smtp_1
odoo_1  | doodba INFO: Waiting until postgres is listening at staging.amazon.rds...
odoo_1  | doodba INFO: Waiting until postgres is listening at staging.amazon.rds...
```
But a connection never happens from our docker instance to the RDS.. 

Any thoughts on what could be happening here? - our setup normally is working whit this setup.

**Comment by Yajo** [comment]
I see nothing wrong in your configuration. You could try with `VERBOSE=1` on the whiltelist proxy to see if you can debug anything from there.



> PING staging.amazon.rds (192.168.0.4) 56(84) bytes of data.

The IP address it's returning is weird. It seems like the kind of IP that a router would provide to a computer in LAN. Is maybe your docker engine configured to use host networking or some other oddity?

**Comment by pedrobaeza** [comment]
No more news, so closing.
